### ISSUE TITLE
There should be a link to new iron worker ruby library

### ISSUE THREAD

**Issue by richardjortega** [iron-io/iron_worker_ruby#36]
Even on your docs it says to stop using this gem, so you github repo would be wise to reflect that.

Also, you documentation on "Get Started" (at least coming from Heroku) is off since it requires the iron_worker (old gem), and there's not mention to the user to install this in their bundle.

Richard

**Comment by narfanator** [comment]
This gem is still linked from the client libraries list (http://dev.iron.io/worker/libraries/). So, is it depreciated, or what?

**Comment by treeder** [comment]
This is the one to use now, it was undeprecated a year or so ago.
